# Generated by Django 3.2.25 on 2024-07-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_maybe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maybe',
        ),
    ]
