# Generated by Django 3.2.25 on 2024-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_delete_maybe'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='str_text',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
